# Generated by Django 3.1.1 on 2020-10-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('content', models.TextField()),
                ('period', models.IntegerField(choices=[(1, 'Daily'), (2, 'Temporarily'), (3, 'Forever')])),
                ('url', models.URLField()),
            ],
        ),
    ]
