# Generated by Django 3.1.1 on 2020-09-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventViewApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='period',
            field=models.IntegerField(choices=[(1, 'Daily'), (2, 'Temporarily'), (3, 'Forever')]),
        ),
    ]
