# Generated by Django 3.1.1 on 2020-10-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventViewApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
    ]
