# Generated by Django 3.1.1 on 2020-11-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventViewApp', '0005_auto_20201112_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('identifier', models.CharField(default='', max_length=200)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
