# Generated by Django 3.1.2 on 2021-03-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventViewApp', '0007_auto_20210319_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='overview',
            field=models.TextField(blank=True),
        ),
    ]
